# Generated by Django 5.0.2 on 2024-02-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='mon_avis',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
