# Generated by Django 5.0.2 on 2024-02-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_rename_film_watchlist_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='a_regarder_plus_tard',
        ),
    ]
