# Generated by Django 5.0.2 on 2024-02-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_remove_watchlist_a_regarder_plus_tard'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='illustration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
